version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: Europe/Paris
  - package-ecosystem: npm
    directory: "/"
    reviewers:
      - julien-deramond
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: "/test/angular-ngx-echarts"
    labels:
      - dependencies
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      angular-ngx-echarts-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/angular-echarts"
    labels:
      - dependencies
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      angular-echarts-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/react"
    labels:
      - dependencies
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      react-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/vue"
    labels:
      - dependencies
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      vue-all-deps:
        patterns:
          - "*"
