version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
  - package-ecosystem: npm
    directory: "/"
    reviewers:
      - louismaximepiton
      - jacques-lebourgeois
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    rebase-strategy: disabled
  - package-ecosystem: npm
    directory: "/test/angular-ngx-echarts"
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      angular-ngx-echarts-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/angular-echarts"
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      angular-echarts-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/angular-ng-boosted"
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      angular-ng-boosted-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/react"
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      react-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/vue"
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    groups:
      vue-all-deps:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/test/angular-14"
    labels:
      - dependencies
    schedule:
      interval: weekly
      day: friday
      time: "06:00"
      timezone: Europe/Paris
    versioning-strategy: increase
    ignore:
      - dependency-name: "@angular-devkit/build-angular"
    groups:
      angular-14-all-deps:
        patterns:
          - "*"
