name: Report a bug
description: Tell us about a bug or issue you may have identified in ODS Charts.
title: "Provide a general summary of the issue"
labels: [bug]
assignees: "-"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/Orange-OpenSource/ods-charts/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
          required: true
        - label: I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
          required: true
        - label: I have read the [contributing guidelines](https://github.com/Orange-OpenSource/ods-charts/blob/main/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: reduced-test-case
    attributes:
      label: Reduced test cases
      description: Include links [reduced test case](https://css-tricks.com/reduced-test-cases/) links or suggested fixes using [CodePen](https://codepen.io/).
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
  - type: input
    id: version
    attributes:
      label: What version of ODS Charts are you using?
      placeholder: "e.g., v1.0.0"
    validations:
      required: true